name: build-test.yml

on:
  push:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Configure CMake
        run: cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release
      - name: Build CMake
        run: cmake --build build
      - name: Run Tests
        run: ./build/tests/simplejson_test
